inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

#require:
#  - rubocop-packaging
#  - rubocop-performance
#  - rubocop-rails
#  - rubocop-rake
#  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

# Disabled on our repo's to enable polyglot-release
Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 200

# This allows us to read the chmod action in a more reproducible way
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

## Disabled until rubocop-rspec is introduced
#RSpec/MessageSpies:
#  EnforcedStyle: receive

# Hack to make rubocop not flag these (We need to re-analyse these later on)
Naming/MethodName:
  Enabled: false
