inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: disable
  # Keep this inline with the lowest ruby version in the gemspec
  TargetRubyVersion: 3.0
  # Display cop name / style guide references
  DisplayCopNames: true
  DisplayStyleGuide: true

# TODO: [LH] - Investigate this in terms of it not being fixed in rubocop?
Naming/MethodName:
  Enabled: false
