sudo: false
language: ruby
rvm:
- 2.5.1
- 2.4.4
- 2.3.7
- 2.2.10
- jruby-9.1.17.0
script: make default
matrix:
  allow_failures:
  - rvm: jruby-9.1.17.0
jobs:
  include:
  - stage: deploy
    ruby: 2.5.1
deploy:
  skip_cleanup: true
  provider: rubygems
  api_key:
    secure: EFoxx/tPgZ2pZqlR5eDEXYQ4f0Lw/2AhkPEPggdbWbzOHMf8WtTAMvjBXKFhMuxmIqLrjd+Yf2gbcJ9kSG4VAWYRVZKPxz39WCUZso1elrrWu0X6gYVzIXjfTdioauyg3mXP5TOvQrG/GCr3/dGpxsDWHO1pFLIVWjg8GIye6Ic=
  gem: gherkin
  on:
    tags: true
