sudo: false
language: ruby
rvm:
- 2.5.1
- 2.4.4
- 2.3.7
- 2.2.10
- jruby-9.1.17.0
script: make default
matrix:
  allow_failures:
  - rvm: jruby-9.1.17.0
jobs:
  include:
  - stage: deploy
    ruby: 2.5.1
deploy:
  skip_cleanup: true
  provider: rubygems
  api_key:
    secure: lbGG3ygWmwpzdD2dc13CyCQG75KMEhO4++YCKrqosTKo4HO/zHOjMrbSp63Z0sNqq0GE/JvIeRc+U0HZSuSPEsYDCy8OT//ZMiAHkjMa7zD4NRCOPptNSpC+L3JTFSjy98nUrr6Ddmncgjvpt9CCAZexAAXZ/k1X+W2eWQQuq/rgI7QWZpY7U5As1Qu5OIizsG04f/sz+Eivwkn+TvvfhTssMtTUUf0nsasqkULGMYHgPBN5I52ucYhLt1YuUzTypY3u2LcopM5VKGZtRvwnyiBnTrZ1h7zWtbed+zZ5o7B2Ru+xAB2dADdEQCf3Oc3Bf0wTkO48yGEnQqOo+HMD5xrc8azFTd6hilje0mT4b5w1PDNiB7hMAxRZbmBfM9UGlygjr8mPFmVaF7ki2UE/8JLZBZC9frURVkcMzYdzNsWknvsee6o8AklViCym6fUCSuW5WpBUPLE/Z4czBUTqQqwXBFiLYCYNxJmzW+9p0oTwvAQmvcX2arlJB5Vy/YZnWGGKJf/a21fUUoaNKgn3uQ2K7/wDkZqGjBp2wo+dNDmmB3VaOCGe9Y0B6XHOMF6jtJb3noVL8zelks0IEyiwTOTGLelLVmtgdA8lYma1eAWvM48GWBotZJsKGsLdFTxJiTZhCI2AFbbp7hPjntmB+KfxF8CVvbuOUIVb82xbcLw=
  gem: gherkin
  on:
    tags: true
