# Please update /.templates/ruby/.travis.yml in the cucumber/cucumber monorepo
# and sync:
#
#     source scripts/functions.sh && rsync_files
#
sudo: false
language: ruby

rvm:
  - "2.5.1"
  - "2.4.4"
  - "2.3.7"
  - "2.2.10"
  - "jruby-9.1.17.0"

script: make default