language: ruby

rvm:
  - ruby-head
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - jruby-9.1.12.0

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

script: make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: change
    on_failure: always
    on_start: never
