require 'rubygems'
require 'bundler'
Bundler::GemHelper.install_tasks

$:.unshift File.expand_path('../lib', __FILE__)

Dir['./rake/*.rb'].sort.each { |f| require f }

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)

task default: :spec
