# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 73b0f6d59bbfcb75e17a4653d581c9dfaca13969  # frozen: v0.12.5
    hooks:
      - id: ruff-check
        files: "^python/"
        args: [ --select=UP ]
      - id: ruff-format
        files: "^python/"
  - repo: https://github.com/pycqa/flake8
    rev: "e43806be3607110919eff72939fda031776e885a"  # frozen: 7.1.1
    hooks:
      - id: flake8
        files: "^python/"
        args: [ "--toml-config=python/pyproject.toml" ]
        additional_dependencies: [
            "flake8-pyproject",
            "flake8-bugbear",
        ]
