# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 73b0f6d59bbfcb75e17a4653d581c9dfaca13969 # frozen: v0.12.5
    hooks:
      - id: ruff-check
        files: "^python/"
      - id: ruff-format
        files: "^python/"
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 2a7c5cc44508119d0935b71797f61725c41af307 # frozen: 0.8.3
    hooks:
      # Ensure the uv lock file is up to date
      - id: uv-lock
        files: python/pyproject.toml
        args: [--project, python]
