name: gherkin
description: Gherkin parser/compiler for Dart.
version: 0.0.1
homepage: https://github.com/cucumber/gherkin
repository: https://github.com/cucumber/gherkin
issue_tracker: https://github.com/cucumber/gherkin/issues
documentation: https://github.com/cucumber/gherkin/tree/main/dart

funding:
  - https://opencollective.com/cucumber
  - https://github.com/sponsors/cucumber

environment:
  sdk: ^3.7.0

topics:
  - cucumber
  - gherkin
  - testing
  - parser

dependencies:
  characters: ^1.1.0
  cucumber_messages: ^33.0.4
  meta: ^1.16.0
  path: ^1.8.0
  uuid: ^4.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.31.0

