language: node_js
node_js:
  - 8.1.4

script: make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: change
    on_failure: always
    on_start: never
