dist: trusty
language: c
sudo: required
compiler:
  - clang
  - gcc
  - i686-w64-mingw32-gcc

before_install:
  - sudo dpkg --add-architecture i386
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y mingw32
  - sudo apt-get install -q -y mingw-w64
  - sudo apt-get install --no-install-recommends -y wine1.8

script: make CC=${CC}

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: change
    on_failure: always
    on_start: never
