---
name: cucumber_gherkin
version: 0.1.0
namespace: cucumber
std: 17
packages:
  cmake:
    - nlohmann_json
    - cucumber_messages
deps:
  - nlohmann/json@v3.11.3:
      args:
        - -DJSON_BuildTests=OFF
        - -DJSON_Install=ON
  - cucumber/messages@main:
      srcdir: cpp
