# Please update /.travis/javas/.travis.yml in the cucumber/cucumber monorepo
# and sync:
#
#     source scripts/functions.sh && rsync_files
#
sudo: false
language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
