language: python
sudo: false

python:
  - "2.7"
  - "3.4"
install: "pip install -r requirements.txt"

script: make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: change
    on_failure: always
    on_start: never
