language: perl
sudo: false

perl:
  - "5.8"
  - "5.20"
install:
  - ( dzil authordeps --missing | cpanm --no-skip-satisfied )
  - ( dzil listdeps --author --missing | cpanm --no-skip-satisfied )
  - make .cpanfile_dependencies

script: make

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: change
    on_failure: always
    on_start: never
