
requires "perl", "5.14.4";
requires "Cpanel::JSON::XS";
requires "Class::XSAccessor";
requires "Cucumber::Messages", ">= 22.0.0, < 29.0.0";
requires "Data::UUID";
requires "Getopt::Long", "2.58";
requires "List::Util", "1.70";

on 'test' => sub {
    requires "Path::Class";
    requires "Test::More";
    requires "Test2::V0";
    requires "Test2::Tools::ClassicCompare";
};

on 'develop' => sub {
    requires "Dist::Zilla";
};
