name: Release Elixir hex package

permissions: {}

on:
  push:
    branches: [release/*]

jobs:
  create-hex-release:
    name: Publish to hex.pm
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: '27.3'
          elixir-version: '1.17'

      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0

      - uses: cucumber/action-publish-hex@ea3883bd0b3d07d9144cbd26274d7e2a0c619780 # v1.0.0
        with:
          hex-api-key: ${{ secrets.HEX_API_KEY }}
          working-directory: 'elixir'
