name: Release RubyGems

permissions: {}

on:
  push:
    branches: [release/*]

jobs:
  publish-rubygem:
    name: Publish Ruby Gem
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: '4.0.2'
      - uses: cucumber/action-publish-rubygem@d8918cbdee789cfc78f346a96a59596b87795be1 # v1.0.0
        with:
          rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          working_directory: ruby
