name: Release NPM

permissions: {}

on:
  push:
    branches: [release/*]


jobs:
  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: npm install-ci-test
        working-directory: javascript
      - run: npm publish
        working-directory: javascript
