name: Release Python

permissions: {}

on:
  push:
    branches: [release/*]

jobs:
  publish-pypi:
    name: Publish PyPI Package
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false
          python-version: "3.13"
          version: "0.11.20"

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish
