name: Release pub.dev

permissions: {}

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1.8.1
      - run: dart pub get --enforce-lockfile
        working-directory: dart
      - run: dart pub publish --dry-run
        working-directory: dart
      - run: dart pub publish --force
        working-directory: dart
