name: Release RubyGems

permissions: {}

on:
  push:
    branches: [release/*]

jobs:
  publish-rubygem:
    name: Publish Ruby Gem
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@6ca151fd1bfcfd6fe0c4eb6837eb0584d0134a0c # v1.290.0
        with:
          ruby-version: '3.4.9'
      - uses: cucumber/action-publish-rubygem@d8918cbdee789cfc78f346a96a59596b87795be1 # v1.0.0
        with:
          rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          working_directory: ruby
