name: Release Python

permissions: {}

on:
  push:
    branches: [release/*]

jobs:
  publish-pypi:
    name: Publish PyPI Package
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
        with:
          enable-cache: false
          python-version: "3.13"
          version: "0.11.28"

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish
