name: Release Python

permissions: {}

on:
  push:
    branches: [release/*]

jobs:
  publish-pypi:
    name: Publish PyPI Package
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: false
          python-version: "3.13"
          version: "0.11.7"

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish
