name: test-python

permissions: {}

defaults:
  run:
    working-directory: python

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - python/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - python/**
      - testdata/**
      - .github/**

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.14"
          - "3.13"
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "0.11.32"

      - name: Lint code
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run --no-editable coverage run -m pytest

      - name: Run acceptance tests
        run: make acceptance

      - name: Build package
        run: uv build
