name: test-ruby

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - ruby/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - ruby/**
      - testdata/**
      - .github/**

jobs:
  test-ruby:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby: ['3.2', '3.3', '3.4']
        include:
          - os: macos-latest
            ruby: '3.4'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ruby
      - run: bundle exec rake
        working-directory: ruby
      - run: make acceptance
        working-directory: ruby
