name: test-c

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - c/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - c/**
      - testdata/**
      - .github/**

jobs:
  test-c:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: run acceptance tests
        run: make acceptance
        working-directory: c
