name: test-dotnet

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - dotnet/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - dotnet/**
      - testdata/**
      - .github/**

jobs:
  test-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - run: dotnet test
        working-directory: dotnet

      - name: run acceptance tests
        run: make acceptance
        working-directory: dotnet
