name: test-dart

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - dart/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - dart/**
      - testdata/**
      - .github/**

jobs:
  test-dart:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: install dart
        uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2

      - name: run tests
        run: dart test
        working-directory: dart
