name: test-elixir

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - elixir/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - elixir/**
      - testdata/**
      - .github/**

jobs:
  test-elixir:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: '27.1'
          elixir-version: '1.17'
      - run: |
          mix deps.get
        working-directory: elixir

      - run: mix test
        working-directory: elixir

      - name: run acceptance tests
        run: make acceptance
        working-directory: 'elixir'
