name: test-perl

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - perl/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - perl/**
      - testdata/**
      - .github/**

jobs:
  test-perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - "5.14"
          - "5.36"

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@a198315ec4e9244f206879ea7b63078003aec8a6 # v1.41.1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm
          working-directory: perl

      - name: run tests
        run: make test
        working-directory: perl

      - name: run acceptance tests
        run: make acceptance
        working-directory: perl
