name: test-dotnet

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - dotnet/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - dotnet/**
      - testdata/**
      - .github/**

jobs:
  test-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - run: dotnet test
        working-directory: dotnet

      - name: run acceptance tests
        run: make acceptance
        working-directory: dotnet
