name: test-dart

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - dart/**
      - testdata/**
      - gherkin-languages.json
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - dart/**
      - testdata/**
      - gherkin-languages.json
      - .github/**

jobs:
  test-dart:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        dart: ["3.8.0", "3.12.0"]
        include:
          - os: windows-latest
            dart: "3.12.0"
          - os: macos-latest
            dart: "3.12.0"

    defaults:
      run:
        working-directory: dart

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
        with:
          sdk: ${{ matrix.dart }}

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze

      - name: Test
        run: dart test

      - name: Run acceptance tests
        run: make acceptance

      - name: Verify publishable package
        run: dart pub publish --dry-run
